import { Autor } from '../entities';

export const IDIOMAS = [
  'Spanish',
  'French',
  'Japanese',
  'German',
  'Korean',
  'Hindi',
  'Italian',
  'Chinese',
  'Russian',
  'Arabic',
  'Portuguese',
  'Turkish',
  'Dutch',
  'Vietnamese',
  'Ukrainian',
  'Greek',
  'Polish',
  'Swedish',
  'Latin',
  'Irish',
  'Norwegian',
  'Hebrew',
  'High Valyrian',
  'Indonesian',
  'Danish',
  'Finnish',
  'Romanian',
  'Hawaiian',
  'Czech',
  'Welsh',
  'Haitian Creole',
  'Swahili',
  'Scottish Gaelic',
  'Hungarian',
  'Esperanto',
  'Klingon',
  'Zulu',
  'Navajo',
  'Yiddish',
];

export const CATEGORIAS = [
  'adventure',
  'biography',
  'business',
  "Children's literature",
  'Classics',
  'comedy',
  'crime',
  'Culture',
  'detective',
  'documentary',
  'drama',
  'fairytale',
  'fantasy',
  'fiction',
  'folk tale',
  'gothic horror',
  'historical',
  'Historical fiction',
  'horror',
  'Human interest',
  'Human interest; Culture',
  'Human interest; Historical',
  'love story',
  'Movies',
  'mystery',
  'non-fiction',
  'novel',
  'novella',
  'Romance',
  'satire',
  'science',
  'science fiction',
  'Short stories',
  'short-story',
  'Sports',
  'tale',
  'Technology &amp; Science',
  'thriller',
  'true stories',
  'Young life/adventure',
];

export const TAGS = [
  'accident',
  'adopting',
  'adult',
  'adventure',
  'Africa',
  'agents',
  'airplane',
  'airport',
  'alien',
  'amnesia',
  'amusing',
  'animals',
  'assassination attempt',
  'asylum',
  'Australia',
  'beach',
  'betrayal',
  'biography',
  'blackmail',
  'business',
  'cartoon',
  'celebrity',
  'children',
  'children-literature',
  'Christmas',
  'classic',
  'collection',
  'colony',
  'comedy',
  'comics',
  'competition',
  'computers',
  'conspiracy',
  'cooking',
  'couple',
  'court',
  'creation',
  'crime',
  'culture',
  'curse',
  'cyberpank',
  'disappearance',
  'disaster',
  'divorce',
  'doctor',
  'documentary',
  'drama',
  'dream',
  'drugs',
  'dystopia',
  'ecology',
  'Edinburgh',
  'Egypt',
  'England',
  'escape',
  'factory',
  'fairy-tale',
  'family',
  'fantasy',
  'farm',
  'fiction',
  'fight',
  'filmed',
  'first-person story',
  'flight',
  'football',
  'France',
  'friendship',
  'friendships',
  'funny',
  'future',
  'geisha',
  'genius',
  'ghost',
  'gothic',
  'government',
  'Greece',
  'grief',
  'Halloween',
  'health',
  'hero',
  'historical',
  'historical fiction',
  'holiday',
  'Hollywood',
  'horror',
  'house',
  'hypnosis',
  'India',
  'inheritance',
  'inspector',
  'inspire',
  'investigation',
  'ironic',
  'island',
  'Italy',
  'jewels',
  'journalist',
  'journey',
  'Kenya',
  'kidnap',
  'kindness',
  'king',
  'knight',
  'law',
  'legend',
  'life-story',
  'love',
  'love-story',
  'madness',
  'magic',
  'marriage',
  'memoirs',
  'misery',
  'missing',
  'murder',
  'music',
  'musical',
  'mystery',
  'Mystic',
  'myth',
  'nature',
  'New Year',
  'Norse mythology',
  'notables',
  'nurse',
  'ocean',
  'office',
  'orphan',
  'photograph',
  'pickpocket',
  'pirates',
  'play',
  'poison',
  'police',
  'politics',
  'poverty',
  'prison',
  'private detective',
  'psychological',
  'puzzle',
  'ransom',
  'relationships',
  'reporter',
  'resort',
  'revenge',
  'revolution',
  'rituals',
  'robbery',
  'romantic',
  'sarcasm',
  'satire',
  'school',
  'science',
  'science-fiction',
  'Scotland',
  'sea-story',
  'secret',
  'security',
  'servants',
  'shark',
  'short',
  'short-story',
  'shot',
  'show',
  'sign up',
  'society',
  'sorrow',
  'space',
  'sport',
  'spouses',
  'spy',
  'Sri-Lanka',
  'stealing',
  'storybook',
  'suffering',
  'suicide',
  'suit',
  'superhero',
  'supernatural',
  'surviving',
  'suspicion',
  'Switzerland',
  'tale',
  'technology',
  'teenager',
  'Thames',
  'thriller',
  'time-travelling',
  'tragedy',
  'treachery',
  'treasure',
  'trial',
  'undead',
  'university',
  'USA',
  'utopia',
  'vacation',
  'vampires',
  'Victorian',
  'vikings',
  'voodoo',
  'war',
  'waxwork',
  'work',
  'writer',
  'zombie',
];

export const AUTORES: Autor[] = [
  {
    nome: 'Antoinette Moses',
    userId: '1',
    descricao:
      'Antoinette Moses is a writer and playwright. Her plays have won several competitions and have been produced or received rehearsed readings in Norwich, Cambridge, Ipswich, London and Paris. Her books range from media studies and poetry to a guidebook to Athens, where she lived for four years.',
  },
];
